### ISSUE TITLE
Can we support case-insensitive?

### ISSUE THREAD

**Issue by sohaha** [quasilyte/phpgrep#57]

**Comment by quasilyte** [comment]
Hello. Could you provide some pattern examples and what they're supposed to match with the case-insensitive mode?

**Comment by sohaha** [comment]
```php
<?php
class a
{
    public static function js()
    {
    }
}

a::js();

a::Js();

A::js();

a::JS();

// they should be the same
```


```bash
phpgrep test.php 'a::js()'

# test.php:9: a::js()
```

**Comment by quasilyte** [comment]
Interesting! This sounds useful.

**Comment by quasilyte** [comment]
You can try building the phpgrep from master branch.

It will do a case insensitive matching by the default as I think it's a more common case when you want `f()` to match both `f()` and `F()`. If case sensitive matching is required, it can be enabled with `-case-sensitive` flag.

**Comment by sohaha** [comment]
perfect 👍
